# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PetCare' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HolaLove
  pod 'SOTabBar'
  pod 'LanguageManager-iOS'
  pod 'LZViewPager'
  pod 'M13Checkbox'
  pod 'RangeSeekSlider'
  pod 'ImageSlideshow'
  pod "ImageSlideshow/Alamofire"
  pod 'UIFloatLabelTextView'
  pod 'MessageKit', '~> 3.3.0'
  pod 'ALCameraViewController'
  pod 'OTPFieldView'
  pod "FlagPhoneNumber"
  pod 'SCLAlertView'
  pod 'ProgressHUD'
  
  pod 'BottomPopUpView'
  pod 'FBSDKLoginKit'

  # Material design
  pod 'MaterialComponents'

  # Pods for PetCare

end
