# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'PetCare' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HolaLove
  pod 'SOTabBar'
  pod 'LanguageManager-iOS'
  pod 'LZViewPager'
  pod 'M13Checkbox'
  pod 'RangeSeekSlider'
  pod 'ImageSlideshow'
  pod "ImageSlideshow/Alamofire"
  pod 'UIFloatLabelTextView'
  pod 'MessageKit', '~> 3.3.0'
  pod 'ALCameraViewController'
  pod 'OTPFieldView'
  pod "FlagPhoneNumber"
  pod 'SCLAlertView'
  
  pod 'BottomPopUpView'
  pod 'FBSDKLoginKit'

  # Material design
  pod 'MaterialComponents'

  # Pods for PetCare

end

post_install do |installer|
    installer.generated_projects.each do |project|
        project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
            end
        end
    end
end
